name: Build and Push Image
description: 'Build and push image to ECR'

inputs:
  tags:
    description: "List of tags"
    required: true
  labels:
    description: "List of metadata for an image"
    required: true
  file:
    description: "Path to the Dockerfile"
    required: true
  cache-from:
    description: "List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)"
    required: false
  platforms:
    description: "List of target platforms for build"
    required: false
  context:
    description: "Create new Context for builder"
    required: false
    default: 'true'
  context_path:
    description: "Build's context is the set of files located in the specified PATH or URL"
    required: false
  target:
    description: "Sets the target stage to build"
    required: false
  role-to-assume:
    description: "The Amazon Resource Name (ARN) of the role to assume"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Context for Buildx
      if: ${{ inputs.context == 'true' }}
      shell: bash
      run: |
        if ! [[ $(docker context ls) =~ builders ]]; then
          docker context create builders
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        endpoint: builders

    - name: Configure AWS credentials (ap-southeast-1)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ap-southeast-1

    - name: Log in to ECR (ap-southeast-1)
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        file: ${{ inputs.file }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: type=inline
        platforms: ${{ inputs.platforms }}
        target: ${{ inputs.target }}
        context: ${{ inputs.context_path }}
